### ISSUE TITLE
Refactor code in BasicFileParser class

### ISSUE THREAD

**Issue by MikeWarren2014** [MikeWarren2014/GithubCodeDocGenerator#1]
**Current code situation**

- Nearly all code for parsing lines of code is contained in `BasicFileParser.parseNextSection()`
- A few helper functions already exist, to some degree of implementation, in class `BasicFileParser`:
  -  `parseFunction()` : not at all implemented and may not be needed
  -  `parseVariables()` : overloaded. 
     -  `parseVariables(String)` : fully implemented
     - `parseVariables(String, int)` : currently a stub
  - `isKeyword()` : fully implemented
  - `isComment()` : fully implemented
  - `isPrimitiveDataType()` : fully implemented
  - `findFirstCommentSymbolIndex()` : overloaded
    - `findFirstCommentSymbolIndex(String)` : fully implemented
    - `findFirstCommentSymbolIndex(String, int)` : fully implemented, but needs refactoring
  - `getCommentTypeAt()` : fully implemented

**TODO list**

- [ ] move working code that handles variables from `parseNextSection()` to `parseVariables()`
- [ ] add helper functions to reduce the number of lines of code in variable-parsing function
  - reminder: max length of function is 50 lines
- [ ] make variable-parsing function more robust
  - needs to handle the following use cases:
    - variable declarations on multiple lines
    - variable declaration list not suffixed by `;`
    - variable list suffixed by multiline comment (improve comment-handling logic)
- [ ] add support for skipping functions,variables
